name: beesect
description: Port of the Python bisect library to the Dart language designed
  specifically for sectarian bees.
repository: https://github.com/rtmigo/beesect_dart

version: 0.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # none :)

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.5.1
