name: beesect
#publish_to: none
description: Port of the Python bisect library to the Dart language.
repository: https://github.com/rtmigo/beesect_dart

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # none :)

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.5.1
