name: bisection
description: Searching in sorted lists. Adding items while maintaining
  the sort order. Port of the Python bisect library.

repository: https://github.com/rtmigo/bisection_dart

version: 0.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # none :)

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.5.1

